### ISSUE TITLE
R 3.6.0

### ISSUE THREAD

**Issue by jwbowers** [markmfredrickson/RItools#106]
Hi All,

Got this message concerning our package (among others):

> R 3.6.0 will be released on Friday and contains changes to the random 
sample() generation which affects comparison with reference output 
(mainly .Rout.save files) in these packages.  Since CRAN expects clean 
output with current R (rather than  past nor future versions), please 
update the package as soon as possible after Friday -- you may want to 
make the package depend on R (>= 3.6.0) as several packages currently in 
3.6.0/Other have done.  Before May 12 to safely retain the package on CRAN.

**Comment by benthestatistician** [comment]
1. I'd sooner just retire all of that tests/*.R and tests/*.Rout.save
nonsense than make the package depend on R version 3.6.0.
2. Or, just add those file patterns to .Rbuildignore, assuming we still
care to run that check locally.

>

**Comment by jwbowers** [comment]
Good point, Ben. Making it depend on the latest R will cause trouble in
bigger hosted environments.

Jake Bowers
http://jakebowers.org

**Comment by markmfredrickson** [comment]
We have a version of `balanceTest`, the spiritual successor to `xBalance` in master right now. I'd lean away from releasing it with this version. Any other thoughts?

**Comment by benthestatistician** [comment]
I agree with Mark.

>

**Comment by jwbowers** [comment]
Sounds good. It would be nice to get it released soonish. But happy to just
make CRAN happy first. So: What are our next steps on this? Remove the
tests? Or just add to .Rbuildignore?

Jake Bowers
http://jakebowers.org

**Comment by benthestatistician** [comment]
I'd say just fish out that branch we created for the last time we patched
to satisfy CRAN maintainers, add the files to its add to .Rbuildignore,
confirm that they're excluded from the tarball and resubmit.

>

**Comment by markmfredrickson** [comment]
I just wanted to check in about this. It looks like there was a release on 2019-05-26 and the version number is incremented by the final `.1`. On the other hand, the package still seems to be running the text based checks.

**Comment by jwbowers** [comment]
I'm working on this now. Quashing little bugs.

**Comment by benthestatistician** [comment]
Hey @jwbowers , it looks like neither Mark nor I felt ready to release `balanceTest()`. If you feel strongly that it belongs in this release, let us know, and we'll huddle to try to figure out whether we can get comfy w/ that & how.  (For starters we'd need to bump the version no to >= 0.3, per https://semver.org .  But that's just a starter.  Next comes #89, which is conceivably the tip of an iceberg.)

Anyway Jake are you comfortable w/ withholding balanceTest() from this release? 

(@markmfredrickson : if so then there's the question of where to keep `balanceTest()` until it's ready.  It being a burden on the project maintainer to have it in the master branch, we should put it into another one.  Since there are a number of branches involving it, perhaps we could start up a GH Project and an a branch associated with that project.)

**Comment by benthestatistician** [comment]
1. [Here](https://github.com/markmfredrickson/RItools/projects/1) is a GH project for work on `balanceTest()`.  Or rather the start of one; I haven't yet attempted any ordering or organization of its cards.  
2. Also created/pushed a new branch, proj1-balT, for `balanceTest()` along with all else that Jake had touched up for the maintenance release.  (I.e. it's a branch off the master branch shortly after the issue-106 branch was merged into it.) 
3. Remains to either pull `balanceTest()` & immediate friends out of the master branch, or whatever else will be basis for maintenance release, or prep it/them for release.  (The latter still being my firm preference, due to how much is open in the [`balanceTest()` project](https://github.com/markmfredrickson/RItools/projects/1).)

**Comment by jwbowers** [comment]
I'm happy keeping balanceTest out for now. Seems like RItools has been orphaned by CRAN, so worth just getting a basic fix to them. 

So: I'll just make a new branch that is the master as of the last release, ignore the offending tests etc.. given latest checking requirements, and submit that. Ok?

**Comment by jwbowers** [comment]
Submitted to CRAN from issue-106-simple and commit 035eecbd0e . Not closing because waiting to hear from CRAN folks.

**Comment by jwbowers** [comment]
Closing with tag 0.1-17 (the last of the old numbering system) and commit 20520f6880

**Comment by benthestatistician** [comment]
@josherrickson notes that our optmatch maintenance release was processed w/ less bother than this latest RItools release.  He hypothesizes that the difference was that optmatch's check generates no warnings, notes or errors whatsoever.  Perhaps it's worth taking the trouble to bring RItools into a similar state?

**Comment by josherrickson** [comment]
I spent a few minutes this morning addressing the various warnings/notes that appeared. I believe it now checks without exceptions.

**Comment by jwbowers** [comment]
Looks great to me. Thanks much, Josh!

Jake Bowers
http://jakebowers.org
