### ISSUE TITLE
When to merge randomization-distribution (in part) into master?

### ISSUE THREAD

**Issue by jwbowers** [markmfredrickson/RItools#38]
Hi all, I'm interested in using `RItest` in the randomization-distribution branch to enable permutation-based generation of the randomization distribution of test statistics under the sharp null. My group read <http://chrisblattman.com/2015/12/07/if-you-run-field-experiments-this-might-be-paper-that-will-make-it-harder-to-publish-your-work-in-a-few-years/> and are now concerned. I feel like `RItest` is a good and easy way to allay anxiety. Right now, however, to install the randomization-distribution branch I currently say: 

The code here relies on a pre-release version of RItools
<https://github.com/markmfredrickson/RItools>. Because it is not on CRAN it
requires a little work to install. I hope that the following commands work to
install it plus its dependencies. The following code creates a local libraries
directory so that this process does not overwrite any other R libraries you may
have installed on your system. I hope that these commands work on Windows as
well as on Unix/OS X based systems.

```
dir.create("libraries")
.libPaths("libraries") ## make the default place for libraries the local one
install.packages(c("hexbin","xtable","svd","SparseM","abind"))
download.file("https://github.com/markmfredrickson/RItools/releases/download/rand-dist-v1.0/RItools_0.1-12.tar.gz",destfile="RItools_0.1-12.tar.gz")
install.packages("RItools_0.1-12.tar.gz")
```
I also would like people to be able to use the cluster branch of `RItools` for simulation based power analysis and having two versions of RItools installed seems confusifying. 

So, I figured I would raise this issue.

**Comment by josherrickson** [comment]
One alternative to the specialized code would be to convert RItools to use devtools, similar to the work I've done the last few days in Optmatch. Aside from simplifying the Makefile and various test/check/build commands (as well as hopefully simplifying the submission to CRAN), this has the added benefit of enabling code such as

    devtools::install_git("https://github.com/markmfredrickson/RItools", branch="cluster", lib="~/R/libraries")

This would be an easier task than converting Optmatch because 1) I've already figured out the fiddly bits and 2) there's no C/Fortran code in RItools. It would require proper Roxygen documentation of all functions (at least `@export` and similar, to enable proper NAMESPACE creation).

If this is something we're interested in, I can look into it next week.

**Comment by benthestatistician** [comment]
I think it's a good time to starting thinking about merging the
randomization distribution branch material into the master branch.

This won't break `xBalance`, will it? If not, or if we don't think so, then
the next step is to merge the master branch into it, and make sure
everything still works.  (Better yet, merge the clusters branching into it
and do the same.)

gettting on devtools would be nice too, particularly if it's a limited
investment of work given what Josh has already done on optmatch -- but if
we're pushing up the randomization distribution branch material, then this
may be less essential.

**Comment by markmfredrickson** [comment]
In my opinion, the two concerns are: 1) documentation and 2) deciding how much we want to worry about performance.

For (1) , step 1 would be be to make sure we like the API of `RItest` and decide if we want to expose any lower level functions. `RItest` is aimed at evaluating one model on a cartesian product of parameters with one test statistic. The lower level functions are little more flexible, but come at the cost of added complexity. My $0.02 is to just expose `RItest` for now (perhaps giving the output of the function a careful eye) and leave lower level stuff private for now.

For (2), there are a couple of RCpp branches that try to move more work to the C level. I forget their exact status. We can always upgrade the performance at a later date.

> One alternative to the specialized code would be to convert RItools to use devtools, similar to the work I've done the last few days in Optmatch. 

I fully support this.

> This won't break `xBalance`, will it? 

Seems unlikely. We never did any work to rewrite `xBalance` to use any of the RItest components, though this was always a goal. The work in the cluster branch might even move us closer to this goal.

**Comment by benthestatistician** [comment]
It seems to me that the two projects under discussion can both move ahead
at their own paces:

1.  merge the randomization inference and cluster branches, with a view to
later merging the merge back up into master;
2. replace current Makefile w/ a devtools-based setup.

At some point there'll also need to be a merge of these two threads of
development, but in the immediate term I see no reason for whichever is
ready first not to be merged into master.  (In the unlikely event that the
transition to devtools created complications in merging either or both of
randomization inference and cluster branches up into master, so that
merging it into master first had the side-effect of postponing the day that
those developments can be merged into master, then Jake could at least
simplify the recipe that he offers to people for getting access to the
RItools material.)

Marks comment weighs in on some other matters too. As usual, I trust his
instincts.

**Comment by jwbowers** [comment]
I agree. So, next week or Friday night --- after all day meetings today and tomorrow --- I'll try to merge randomization-distribution into cluster and call this a new branch which will be the development branch. The devtools setup definitely sounds great if there is time and energy for it once we have the new branch.

**Comment by jwbowers** [comment]
I have merged from cluster into randomization-distribution and am working on squashing errors that emerge from make check.

**Comment by jwbowers** [comment]
I think that we can close this issue. I think Josh is preparing to merge master into randomization-distribution. Or cluster into randomization-distribution. Then, randomization-distribution can continue separate from master for a bit until we get the documentation for it done and are happy with it in a preliminary way. So, I'm closing this. Happy to have others reopen.
