### ISSUE TITLE
cluster branch versus master branch differences 

### ISSUE THREAD

**Issue by jwbowers** [markmfredrickson/RItools#39]
This may be something that Mark already knows about. However, just in case it is news, I'll add it here.

The results differ between the master branch and the cluster branch. 

## Master branch

In the master branch the adj.diff is the harmonic weighted diff of means, see below how `lm` produces the same answer as `xBalance`.

```
nuclearplants$ptF<-factor(nuclearplants$pt)
> xb<-xBalance(pr~t1,strata=list(pt=~ptF,unstrat=NULL),data=nuclearplants,report="all")
> xb
     strata     pt                                                          unstrat
     stat     pr=0   pr=1 adj.diff adj.diff.null.sd std.diff    z              pr=0   pr=1 adj.diff adj.diff.null.sd std.diff    z
vars
t1          13.395 14.349   0.953            1.204    0.279   0.792          13.636 14.000   0.364            1.285    0.106   0.283
---Overall Test---
        chisquare df p.value
pt         0.6270  1   0.428
unstrat    0.0801  1   0.777

> lm(t1~pr+ptF,data=nuclearplants)

Call:
lm(formula = t1 ~ pr + ptF, data = nuclearplants)

Coefficients:
(Intercept)           pr         ptF1
    14.1279       0.9535      -3.6047
```

## Cluster branch (New Randomization-Distribution branch)
The cluster branch does not do what I expect (i.e. same as `lm` or previous `xBalance`).

```
> nuclearplants$ptF<-factor(nuclearplants$pt)
> xb<-xBalance(pr~t1+strata(ptF),data=nuclearplants,report="all")
> xb
     strata       ptF                                             Unstrat
     stat   Treatment Control adj.diff std.diff    z            Treatment Control adj.diff std.diff    z
vars
t1            14.0000 13.8310  0.1690   0.0457  0.7918            14.0000 13.6364  0.3636   0.0982  0.2830
---Overall Test---
        chisquare df       p.value
ptF     "0.6270"  "1.0000" "0.8569"
Unstrat "0.0801"  "1.0000" "0.8569"
```

**Comment by benthestatistician** [comment]
I think this is all as it should be, but to check, here are the differences
I see:

- `adj.diff.null.sd` has been removed
- Formatting changes in output
- Pooled SDs (ie, denominators of standard differences) are being
calculated differently
- adjusted diffs are being calculated differently, at least for stratified
designs.

Do you see anything besides these?

Comments: Mark and I made the decision that for _descriptive_ statistics we
should move away from weighting on the basis of harmonic means of treatment
and control group sizes, instead weighting on the per-stratum treatment
group sizes. I think this decision pertained to SDs as well as to means;
thus the changes in the pooled SD.

`adj.diff.null.sd` got kicked out b/c it doesn't fit cleanly into our new
division between "descriptives" and "inferentials".  Sorry!

I'll leave the formatting assessment to others who are better qualified to
appraise.  A minor comment is that it would be nice to get rid of the
quotes around the numbers reported under "overall test".

**Comment by jwbowers** [comment]
Thanks for the explanation, Ben!

Maybe I missed the thread on harmonic versus stratum size weights. I had been encouraging the use of xBalance as one way to estimate an ATE. Now we have two different estimates of two different quantities: the harmonic weighted estimate from lm() and the stratum weighted estimate (using a description as an estimate) of a stratum size weighted target from xBalance(). From the perspective of offering methodological advice on estimation in addition to testing, I had argued that the harmonic weight was sensible and that the stratum size weight was also sensible although the confidence interval for the harmonic weighted estimate should be a bit more precise. I guess, we will just have to engage more with the weighting choice issue when we teach about estimation since the numbers shown by lm and xBalance now differ. Did you all come to some conclusion about weighting for estimation in the discussions about the change?

**Comment by benthestatistician** [comment]
`control.avg` is a standardized average (in the [epidemiologists' sense](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/EP/EP713_StandardizedRates/EP713_StandardizedRates4.html) ) of control observations, using the treatment group as the standard population. In other words, a weighted average over the control group, with each control weighted in proportion to the ratio of treatments to controls within its stratum.  

I think that's actually quite a bit easier to explain and understand than the harmonic mean standardization we've been leaning on up to now.  That's one reason I pushed for this change, the other being that the [What Works Clearinghouse's Procedures and Standards Handbook](http://ies.ed.gov/ncee/wwc/documentsum.aspx?sid=19) appears to require it in order for experiments or quasiexperiments to declared to have met their standards with or without reservations, and we'd like for RItools to support that sort of work.

It's important to emphasize that, because we're still using harmonic weights for the inferential statistics, we'll continue to get their precision benefits for tests and confidence intervals formed via `xBalance`. 

(I'm going to go ahead and close this out, in the interest of task list tidiness; do reopen if you deem appropriate.)
