### ISSUE TITLE
SparseMMFromFactor has internally inconsistent results with manually manipulated match

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/RItools#40]
See code below.

    library(optmatch)
    library(SparseM)
    data(nuclearplants)

    m <- pairmatch(pr ~ t1 + t2 + cap, data = nuclearplants)
    m["I"] <- NA

    z <- attr(m, "contrast.group")

    sparsem <- SparseMMFromFactor(m)

    t <- t(as.matrix.csr(z))%*%sparsem
    c <- t(as.matrix.csr(!z))%*%sparsem

    > attr(t, "dimension")
    [1]  1 10
    > attr(c, "dimension")
    [1]  1 10
    > sapply(attributes(t), length)
           ra        ja        ia dimension     class 
           10        10         2         2         1 
    > sapply(attributes(c), length)
           ra        ja        ia dimension     class 
            9         9         2         2         1 

`c` should have 10 objects in `ra` and `ja`; or it should have dimension 1x9 (the former is preferred for my use case).

I'm uncertain if the issue is in `SparseMMFromFactor` or something with `matrix.csr`'s Ops. I suspect the former, but I'd have to dive a lot deeper into the code than I am able to right now to be certain.

**Comment by benthestatistician** [comment]
Interesting. At first I suspected a problem in `SparseMMFromFactor`, whose author didn't think of this situation.  But now that I run the example and look at it, I wonder if there's really a problem?  That missing entry in what @josherrickson calls `c` (which I'll re-title as `ctl`) is a 0, and is perfectly legitimate sparse-matrix-ese to code a 0 as the absence of an entry. And `ctl` seems to behave as a dimension 1x10 matrix should: e.g.

```{r}
tx <- t(as.matrix.csr(z))%*%sparsem
ctl <- t(as.matrix.csr(!z))%*%sparsem
ctl %*% t(tx)
```
this gives a 1x1 sparse matrix, as it should. So, think you can work around the difficulty otherwise?

**Comment by josherrickson** [comment]
You're right Ben - I was thrown off by the dimension and number of entries agreeing - but you're of course correct that that needn't be the case.
